ulubione_gry = {
        'AC': "Assassins's Creed",
        'AC II': "Assassin's Creed II",
        'ACB': "Assassin's Creed: Brotherhood",
        'ACR': "Assassin's Creed: Revelations",
        'AC III': "Assassin's Creed III",
        'AC IV': "Assassin's Creed IV: Black Flag",
        'ACr': "Assassin's Creed: Rogue",
        'ACU': "Assassin's Creed: Unity",
        'ACS': "Assassin’s Creed: Syndicate",
        'NFS' : "Need For Speed",
        'SWB' : "Star Wars Battlefront",
        'SWB2' : "Star Wars Battlefront II",
        'MC' : "Minecraft",
        'WOT' : "World of tanks",
        'WOWS' : "World of warships",
        'WOWP' : "World of warplanes",
        'CSGO' : "Counter-Strike: Global Offensive",
        'Cros' : "Crossout",
        'LEGOB' : "Lego Batman",
        'LEGOB2' : "Lego Batman 2: DC Super Heroes",
        'LEGOB3' : "Lego Batman 3: Poza Gotham",
        'LEGOM' : "Lego Marvel: Super Heroes",
        'BIOHERO' : "Bionicle Heroes",
    }
print('liczba moich ulubionych gier:', len(ulubione_gry))